# HTML Learning Adventure - MkDocs Configuration
site_name: Myra's HTML Adventure
site_description: Myra Kumar's creative coding journey - learning HTML and CSS through art, math, and fun projects
site_author: Myra Kumar
site_url: https://anismiles.github.io/html-learning-adventure

# Repository
repo_name: anismiles/html-learning-adventure
repo_url: https://github.com/anismiles/html-learning-adventure
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  
  # Color palette - Myra's favorite colors: Teal, Purple, Yellow
  palette:
    # Light mode - Teal & Yellow
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode - Deep Purple & Teal
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Typography
  font:
    text: Arimo
    code: Roboto Mono

  # Features
  features:
    - navigation.instant        # Single-page app experience
    - navigation.instant.prefetch  # Prefetch pages for faster loading
    - navigation.tracking       # Update URL with current section
    - navigation.tabs           # Top-level tabs
    - navigation.tabs.sticky    # Sticky navigation tabs
    - navigation.sections       # Group navigation sections
    - navigation.expand         # Expand all sections by default
    - navigation.path           # Show navigation path
    - navigation.top            # Back to top button
    - navigation.footer         # Previous/next navigation in footer
    - toc.follow               # Sidebar follows scroll
    - toc.integrate            # Integrate TOC with navigation
    - search.highlight         # Highlight search terms
    - search.share             # Share search results
    - search.suggest           # Search suggestions
    - content.code.copy        # Copy code blocks
    - content.code.annotate    # Code annotations
    - content.tabs.link        # Link content tabs
    - header.autohide          # Auto-hide header on scroll

  # Logo and favicon (comment out until we add them)
  # logo: assets/images/logo.png
  # favicon: assets/images/favicon.ico

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Setup Guide: setup-guide.md

  - HTML Fundamentals:
    - Chapter 1 - HTML Essentials: chapters/chapter1/index.md
    - Chapter 2 - CSS Styling Fundamentals: chapters/chapter2/index.md
  - Building Projects:
    - Chapter 3 - Page Layout & Organization: chapters/chapter3/index.md
    - Chapter 4 - Working with Files & Folders: chapters/chapter4/index.md
    - Chapter 5 - Tables & Data Organization: chapters/chapter5/index.md
  - Advanced Design:
    - Chapter 6 - Advanced Layout & Design: chapters/chapter6/index.md
    - Chapter 7 - Forms & User Interaction: chapters/chapter7/index.md
    - Chapter 8 - CSS Mastery & Advanced Design: chapters/chapter8/index.md

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  
  # -- For timestamps
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: datetime
  #     fallback_to_build_date: true
  
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          primaryColor: '#2dd4bf'
          primaryTextColor: '#ffffff'

# Markdown extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: anismiles
      repo: html-learning-adventure
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab

# Extra CSS and JavaScript
# extra_css:
#   - stylesheets/extra.css

# extra_javascript:
#   - assets/js/custom.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra configuration
extra:
  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anismiles/html-learning-adventure
  
  # Version info
  version:
    provider: mike
    default: latest
  
  # Analytics (optional)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX  # Replace with your Google Analytics ID

# Copyright
copyright: |
  Copyright &copy; 2024 Myra Kumar<br>
  <small>Built with teal, purple, and yellow love for a young artist-developer, Myra!</small>

# Custom configuration for educational content
strict: false  # Allow warnings for now

# Watch files for live reload during development
watch:
  - docs/
  - mkdocs.yml
